pretrained: 1
dataset: 'ShapeIntersection'
model: 'DMN'
batch_size: 128
run: 1
num_epochs: 800
embedding_size: 256
learning_rate: 0.001
num_hops: 3
early_stopping_epoch: 80
save_path: './results'
l2_reg: 0.1
dropout_reg: 0.9
abl_number: 1
data_path: './data_ShapeIntersection'
reg: 1
per_inter_sup: 1
